name: Crafticity
version: 1
main: com.AltraDev.Crafticity.Crafticity
description: The main plugin for the crafticity server.
commands:
    test:
        usage: /<command>
        description: Test command dur dur.
permissions: