name: Crafticity
version: 1
main: com.AltraDev.Crafticity.Crafticity
description: The main plugin for the crafticity server.
commands:
    test:
        usage: /<command>
        description: Test command dur dur.
    warning:
        usage: /<command> <type> <level> <message> <player>
        description: Warn staff about hackers or something!
permissions:
    crafticity.warning:
        description: Permission to do /warning!
        default: op