name: Crafticity
version: 1
main: com.AltraDev.Crafticity.Crafticity
description: The main plugin for the crafticity server.
commands:
    poke:
        usage: /<command>
        description: Poke other players.
    svr:
        usage: /<command>
        description: Spawn a villager
permissions:
   