name: Crafticity
version: 1
main: com.AltraDev.Crafticity.Crafticity
description: The main plugin for the crafticity server.
commands:
    poke:
        usage: /<command>
        description: Poke other players.
    serverbook:
        usage: /<command>
        aliases: [sb]
        description: Testing books
    admingem:
        usage: /<command>
        description: Admingem for staff!
    ieffect:
        usage: /<command>
        description: Enables you to create infinite potion effects
    iclear:
        usage: /<command>
        description: Lets you clear all potion effects
    
permissions:
    crafticity.admingem.use:
        description: Admingem use
        default: op
    crafticity.ieffect:
        description: Ability to create infinite potion effect
        default: op
    crafticity.iclear:
        description: Ability to clear all potion effects
        default: op
    crafticity.poke:
        description: Poke someone
        default: op